name: Deploy Preprod

on:
  push:
    branches:
      - edge

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "polis-preprod"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: "edge"
          
      - name: Deploy to Heroku
        run: |
          git push https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/polis-preprod.git edge:main

  deploy-static:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Build static assets
        env:
          EMBED_SERVICE_HOSTNAME: preprod.pol.is
          ENABLE_TWITTER_WIDGETS: true
          GA_TRACKING_ID: G-WVP78N35QR
          SERVICE_URL: https://preprod.pol.is
        run: |
          docker compose create --build --force-recreate file-server
          docker cp file-server:/app/build/build ./build

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -r deploy/requirements.txt

      - name: Deploy to S3
        run: |
          python deploy/deploy-static-assets.py --bucket edge.static-assets.pol.is
